### ISSUE TITLE
Cicada barbara barbara in Spain?

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/hoppers#4]
https://hoppers.speciesfile.org/otus/8751/overview both subspecies occur in Spain? C.b. lusitanica also in Brazil?

**Comment by proceps** [comment]
distribution in brasil was based on a catalogue record, I checked the original publication of the record, and it is a clear mistake in catalogue. In the paper, the subspecies was reported from Portugal.

**Comment by klausriede** [comment]
that´s what user comments are for! We still need map references, ie clicking on Brazil one should see the origin of the info

**Comment by proceps** [comment]
At the moment, it could be done by downloading DwC Archive, which should have all the references. For the genus, you can also use Search functionality on the map, so that when you select a country, you will get a list of OTUs. Please submit a detailed suggestion for TaxonPage development. https://github.com/SpeciesFileGroup/taxonpages/issues
